name: Close empty issues

on:
  issues:
    types:
      - edited
      - opened

jobs:
  empty-issues-closer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        with:
          close_comment: "Closed!"
